services:
  - type: web
    name: format1
    runtime: node
    repo: https://github.com/flager666/format1
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: GEMINI_API_KEY
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: GEMINI_API_KEY_FREE
        sync: false
    autoDeployTrigger: commit
    rootDir: ./
